# Generated by Django 5.0.7 on 2024-07-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_img',
            new_name='profile_picture',
        ),
    ]
